version: '3'
services:

  #REMEMBER to Build target
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    container_name: sem_demo_app
    volumes:
    - .\target\classes:/tmp